const path = require('path');
const express = require('express');
const { default: mongoose } = require('mongoose');
const app = express();
const PORT = 4444;
require('dotenv').config()

const passport = require('./passport/passport');
const isLoggedIn = require('./middlewares/isLoggedIn');
const isLoggedOut = require('./middlewares/isLoggedOut');
const session = require('express-session');

var MongoDBStore = require('connect-mongodb-session')(session);
var store = new MongoDBStore({
    uri: 'mongodb://127.0.0.1:27017/myapp',
    collection: 'mySessions'
});

app.use(session({
    secret: 'abdfrv jhrjewrjwerje',
    resave: true,
    saveUninitialized: true,
    store: store,
}));


app.use(passport.initialize());
app.use(passport.session());


app.set('view engine', 'hbs');
app.use(express.urlencoded({ extended: true }));

// Way to user routers
app.get('/login', (req, res) => {
    res.redirect('/auth/login');
})
app.use('/auth', isLoggedOut, require('./routers/auth'));
app.use('/', isLoggedIn, require('./routers/user'));

app.post('/logout', function (req, res, next) {
    req.logout(function (error) {
        if (error) {
            return res.render('error', {
                error
            })
        }
        res.redirect('/auth/login');
    });
});


mongoose.connect('mongodb://localhost:27017/myapp')
    .then(() => {
        app.listen(PORT, () => {
            console.log(`http://localhost:` + PORT);
        });
    })
/*
Ye code ek Express.js app hai jo Passport.js aur MongoDB-backed session store ke saath authentication handle karta hai.
---

### **Notes: MongoDB Session Store with Passport.js**

**1. Default session behavior (in-memory)**

```js
app.use(session({
    secret: 'secret',
    resave: true,
    saveUninitialized: true
}));
```

* Stores session **in server memory**.
* Problems:

  * Lost on server restart → users logged out.
  * Not scalable → multi-server apps cannot share session state.

---

**2. Using MongoDB for session storage**

```js
var MongoDBStore = require('connect-mongodb-session')(session);
var store = new MongoDBStore({
    uri: 'mongodb://127.0.0.1:27017/myapp',
    collection: 'mySessions'
});

app.use(session({
    secret: 'secret',
    resave: true,
    saveUninitialized: true,
    store: store
}));
```

**How it works:**

* `connect-mongodb-session` creates a **MongoDB-backed session store**.
* Each session is saved as a **document in MongoDB**.
* Passport stores **minimal info in the session**, usually `user._id` inside:

```json
passport: { "user": "64fae2b4e3f1c5a1f0a12345" }
```

---

**3. How MongoDB stores it internally**

A typical session document in the `mySessions` collection:

```json
{
  "_id": "sessionId123",             // Unique session ID generated by express-session
  "session": {
    "cookie": {                      // Cookie info (expires, path, etc.)
      "originalMaxAge": 3600000,
      "expires": "2025-11-24T10:00:00Z",
      "httpOnly": true,
      "path": "/"
    },
    "passport": {                     // Passport-specific session info
      "user": "64fae2b4e3f1c5a1f0a12345"  // The ID stored via serializeUser
    }
  },
  "expires": "2025-11-24T10:00:00Z"  // MongoDB TTL for auto-deletion
}
```

* `_id` → maps to the session cookie sent to the client.
* `session.passport.user` → stores the user identifier (from `serializeUser`)
* `expires` → TTL for automatic session removal

---

**4. Advantages over default memory store**

| Feature                     | In-Memory Store      | MongoDB Store                   |
| --------------------------- | -------------------- | ------------------------------- |
| Persistence                 | ❌ Lost on restart    | ✅ Survives restarts             |
| Scalability                 | ❌ Single server only | ✅ Works across multiple servers |
| Session lifetime management | Limited              | ✅ TTL supported in MongoDB      |
| Integration with Passport   | ✅                    | ✅                               |

---

**5. Passport + MongoDB session flow**

1. **Login**

   * LocalStrategy authenticates user
   * `serializeUser(user, done)` stores `user._id` in session → stored in MongoDB

2. **Request after login**

   * `express-session` reads session from MongoDB using cookie ID
   * `passport.session()` middleware detects `passport.user` → calls `deserializeUser(userId, done)`
   * `req.user` is populated

3. **Logout**

   * `req.logout()` removes `passport.user` from session → session still exists in MongoDB, but no user attached

---
*/